kind: "Service"
apiVersion: "v1"
metadata:
  name: "icxpoc-proj1-dev-svc"
spec:
  ports:
    -
      name: "web"
      protocol: "TCP"
      port: 8080
  selector:
    name: "icxpoc-proj1-dev"
  type: "ClusterIP"
  sessionAffinity: "None"
---
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "icxpoc-proj1-dev"
spec:
  template:
    metadata:
      labels:
        name: "icxpoc-proj1-dev"
      annotations:
        app_version: 'latest'
    spec:
      containers:
        -
          name: "icxpoc-proj1-dev"
          image: "containers.cisco.com/it_cits_csas/icxpocdeploy_icxpoc-proj1:__IMAGETAG__"
          ports:
            -
              containerPort: 8080
              protocol: "TCP"
          env:
            -
              name: "APP_NAME"
              value: "icxpoc-proj1-dev"
            -
              name: "CISCO_LC"
              value: "dev"

            - name: "MONGODB_PASSWORD"
              valueFrom:
                  secretKeyRef:
                    name: "mongo-secret"
                    key: "password"

            - name: "MONGODB_USER"
              valueFrom:
                  secretKeyRef:
                    name: "mongo-secret"
                    key: "username"

            - name: "MONGO_APP_NAME"
              value: "cdcsmbprodrepo-nqonxs3xdev-3-cdcsmbprodrepo.cloudapps.cisco.com"

            - name: "MONGO_PORT"
              value: "35641"

            - name: "MONGODB_DATABASE"
              value: "Personalization"
              
            - name: "MONGODB_CLOUD_PASSWORD"
              valueFrom:
                  secretKeyRef:
                    name: "mongo-cloud-secret"
                    key: "password"

            - name: "MONGODB_CLOUD_USER"
              valueFrom:
                  secretKeyRef:
                    name: "mongo-cloud-secret"
                    key: "username"
                    
            - name: "MONGO_REPLICA_HOSTS"
              value: "mgdb-cdcdev-npd1-1.cisco.com:27060,mgdb-cdcdev-npd2-1.cisco.com:27060,mgdb-cdcdev-npd3-1.cisco.com:27060" 

            - name: "MONGO_REPLICA_SET"
              value: "cdcdevnpdrs"               

          volumeMounts:
            -
              name: podinfo
              mountPath: /etc/metadata
              readOnly: false
          imagePullPolicy: "IfNotPresent"
          securityContext:
            capabilities: {}
            privileged: false
          #readinessProbe:
          #  httpGet:
          #    path: "/"
          #    port: 8080
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
          #livenessProbe:
          #  exec:
          #    command:
          #      - "/bin/true"
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
      volumes:
        -
          name: podinfo
          downwardAPI:
            items:
              -
                path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              -
                path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
      restartPolicy: "Always"
      dnsPolicy: "ClusterFirst"
  replicas: 1
  selector:
    name: "icxpoc-proj1-dev"
  triggers:
    -
      type: "ConfigChange"
  strategy:
    type: "Rolling"
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 120